version: '3'
services:
  echoserver:
    build:
      context: .
    ports:
      - "6000:6000"
  nginx:
    build:
      context: ./nginx
    ports:
      - "8088:80"
  redis:
    build:
      context: ./redis
    ports:
      - "6379:6379"
